/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: ImageWithAlt;
  icon?:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users";
  heading?: string;
  description?: string;
  actions?: Array<
    {
      _key: string;
    } & IconLink
  >;
  helpPanel?: {
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogEyebrow?: string;
  ogDescription?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  decorative?: boolean;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  avatars?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  socialProof?: {
    prefix?: string;
    highlightSuffix?: string;
    suffix?: string;
  };
  closingBand?: ClosingBand;
  cta?: CtaBanner;
  seo?: Seo;
};

export type CtaBanner = {
  _type: "ctaBanner";
  title?: string;
  description?: string;
  primary?: Link;
  secondary?: Link;
  image?: ImageWithAlt;
};

export type ClosingBand = {
  _type: "closingBand";
  title?: string;
  description?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  searchPlaceholder?: string;
  supportCard?: {
    title?: string;
    description?: string;
    emailLabel?: string;
  };
  closingBand?: ClosingBand;
  cta?: CtaBanner;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  stats?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    inverted?: boolean;
    _type: "aboutStat";
    _key: string;
  }>;
  missionStory?: {
    eyebrow?: string;
    title?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    image?: ImageWithAlt;
    action?: Link;
  };
  craftCards?: Array<{
    title?: string;
    description?: string;
    image?: ImageWithAlt;
    _type: "craftCard";
    _key: string;
  }>;
  specTable?: {
    heading?: string;
    description?: string;
    rows?: Array<{
      type?: string;
      durability?: string;
      idealFor?: string;
      warranty?: string;
      _type: "aboutSpecRow";
      _key: string;
    }>;
  };
  cta?: CtaBanner;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  cta?: CtaBanner;
  seo?: Seo;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  comparisonHeading?: SectionHeading;
  processHeading?: SectionHeading;
  processFootnote?: string;
  cta?: CtaBanner;
  seo?: Seo;
};

export type SectionHeading = {
  _type: "sectionHeading";
  eyebrow?: string;
  title?: string;
  description?: string;
};

export type GalleryProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "galleryProject";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  servicesHeading?: SectionHeading;
  qualityBand?: {
    title?: string;
    description?: string;
    image?: ImageWithAlt;
    statLabel?: string;
    points?: Array<
      {
        _key: string;
      } & IconCard
    >;
  };
  galleryHeading?: {
    eyebrow?: string;
    title?: string;
    link?: Link;
  };
  bentoTiles?: Array<{
    project?: GalleryProjectReference;
    span?: "" | "md:col-span-2" | "md:col-span-2 md:row-span-2";
    _type: "bentoTile";
    _key: string;
  }>;
  faqSection?: {
    heading?: SectionHeading;
    image?: ImageWithAlt;
    link?: Link;
  };
  contactSection?: {
    formTitle?: string;
    formDescription?: string;
    title?: string;
    description?: string;
    channelLabels?: {
      phone?: string;
      email?: string;
      address?: string;
    };
    mapImage?: ImageWithAlt;
  };
  cta?: CtaBanner;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  legalName?: string;
  tagline?: string;
  description?: string;
  blurb?: string;
  keywords?: Array<string>;
  stats?: {
    yearsExperience?: string;
    familiesServed?: string;
  };
  contact?: {
    phone?: string;
    phoneHref?: string;
    email?: string;
    street?: string;
    locality?: string;
    region?: string;
    postcode?: string;
    country?: string;
  };
  hours?: Array<
    {
      _key: string;
    } & OpeningHoursRow
  >;
  hoursSummary?: string;
  openingHoursSpec?: Array<string>;
  serviceAreas?: Array<string>;
  navItems?: Array<
    {
      _key: string;
    } & Link
  >;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type ProcessStep = {
  _id: string;
  _type: "processStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number?: string;
  title?: string;
  description?: string;
  order?: number;
};

export type FaqGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqGroup";
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  group?: FaqGroupReference;
  showOnHome?: boolean;
  order?: number;
};

export type FaqGroup = {
  _id: string;
  _type: "faqGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  icon?:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users";
  order?: number;
};

export type FlooringServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "flooringService";
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type GalleryProject = {
  _id: string;
  _type: "galleryProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  subtitle?: string;
  category?: FlooringServiceReference;
  sector?: "Residential" | "Commercial";
  aspect?:
    | "aspect-[3/4]"
    | "aspect-[4/3]"
    | "aspect-square"
    | "aspect-[4/5]"
    | "aspect-[3/2]";
  image?: ImageWithAlt;
  caseStudy?: CaseStudyReference;
  order?: number;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  category?: FlooringServiceReference;
  eyebrow?: string;
  title?: string;
  shortTitle?: string;
  summary?: string;
  hero?: ImageWithAlt;
  meta?: Array<
    {
      _key: string;
    } & MetaItem
  >;
  challenge?: {
    heading?: string;
    body?: string;
    image?: ImageWithAlt;
  };
  solution?: {
    heading?: string;
    body?: string;
    image?: ImageWithAlt;
    stats?: Array<
      {
        _key: string;
      } & StatChip
    >;
  };
  features?: {
    heading?: string;
    description?: string;
    items?: Array<
      {
        _key: string;
      } & IconCard
    >;
  };
  specs?: {
    heading?: string;
    description?: string;
    rows?: Array<
      {
        _key: string;
      } & SpecRow
    >;
  };
  details?: {
    heading?: string;
    rows?: Array<
      {
        _key: string;
      } & MetaItem
    >;
  };
  roadmap?: {
    heading?: string;
    description?: string;
    steps?: Array<
      {
        _key: string;
      } & IconCard
    >;
  };
  gallery?: {
    heading?: string;
    images?: Array<
      {
        _key: string;
      } & ImageWithAlt
    >;
  };
  testimonial?: {
    quote?: string;
    name?: string;
    role?: string;
    image?: ImageWithAlt;
  };
  cta?: {
    heading?: string;
    description?: string;
    primary?: Link;
    secondary?: Link;
  };
  seo?: Seo;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FlooringService = {
  _id: string;
  _type: "flooringService";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: "hybrid" | "laminate" | "timber";
  name?: string;
  shortName?: string;
  descriptor?: string;
  icon?:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users";
  plankColor?: string;
  homeBlurb?: string;
  homeFeatures?: Array<string>;
  servicesBlurb?: string;
  servicesFeatures?: Array<string>;
  image?: ImageWithAlt;
  specs?: {
    coreMaterial?: string;
    jankaRating?: string;
    thickness?: string;
    installation?: string;
    waterproof?: string;
  };
  order?: number;
};

export type SocialLink = {
  _type: "socialLink";
  icon?: "facebook";
  label?: string;
  href?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type OpeningHoursRow = {
  _type: "openingHoursRow";
  days?: string;
  short?: string;
  time?: string;
  closed?: boolean;
};

export type IconLink = {
  _type: "iconLink";
  icon?:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users";
  label?: string;
  href?: string;
};

export type IconCard = {
  _type: "iconCard";
  icon?:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users";
  title?: string;
  description?: string;
};

export type StatChip = {
  _type: "statChip";
  value?: string;
  label?: string;
};

export type SpecRow = {
  _type: "specRow";
  attribute?: string;
  value?: string;
};

export type MetaItem = {
  _type: "metaItem";
  label?: string;
  value?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | NotFoundPage
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | ContactPage
  | CtaBanner
  | ClosingBand
  | PageHero
  | FaqPage
  | AboutPage
  | Link
  | GalleryPage
  | ServicesPage
  | SectionHeading
  | GalleryProjectReference
  | HomePage
  | SiteSettings
  | ProcessStep
  | FaqGroupReference
  | Faq
  | FaqGroup
  | FlooringServiceReference
  | CaseStudyReference
  | GalleryProject
  | CaseStudy
  | Slug
  | FlooringService
  | SocialLink
  | FooterColumn
  | OpeningHoursRow
  | IconLink
  | IconCard
  | StatChip
  | SpecRow
  | MetaItem
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    name,    legalName,    tagline,    description,    blurb,    keywords,    stats{ yearsExperience, familiesServed },    contact,    hours[]{ days, short, time, closed },    hoursSummary,    openingHoursSpec,    serviceAreas,    navItems[]{ label, href },    footerColumns[]{ title, links[]{ label, href } },    socialLinks[]{ icon, label, href }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      name: null;
      legalName: null;
      tagline: null;
      description: null;
      blurb: null;
      keywords: null;
      stats: null;
      contact: null;
      hours: null;
      hoursSummary: null;
      openingHoursSpec: null;
      serviceAreas: null;
      navItems: null;
      footerColumns: null;
      socialLinks: null;
    }
  | {
      name: string | null;
      legalName: null;
      tagline: null;
      description: null;
      blurb: null;
      keywords: null;
      stats: null;
      contact: null;
      hours: null;
      hoursSummary: null;
      openingHoursSpec: null;
      serviceAreas: null;
      navItems: null;
      footerColumns: null;
      socialLinks: null;
    }
  | {
      name: null;
      legalName: null;
      tagline: null;
      description: string | null;
      blurb: null;
      keywords: null;
      stats: null;
      contact: null;
      hours: null;
      hoursSummary: null;
      openingHoursSpec: null;
      serviceAreas: null;
      navItems: null;
      footerColumns: null;
      socialLinks: null;
    }
  | {
      name: string | null;
      legalName: string | null;
      tagline: string | null;
      description: string | null;
      blurb: string | null;
      keywords: Array<string> | null;
      stats: {
        yearsExperience: string | null;
        familiesServed: string | null;
      } | null;
      contact: {
        phone?: string;
        phoneHref?: string;
        email?: string;
        street?: string;
        locality?: string;
        region?: string;
        postcode?: string;
        country?: string;
      } | null;
      hours: Array<{
        days: string | null;
        short: string | null;
        time: string | null;
        closed: boolean | null;
      }> | null;
      hoursSummary: string | null;
      openingHoursSpec: Array<string> | null;
      serviceAreas: Array<string> | null;
      navItems: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      footerColumns: Array<{
        title: string | null;
        links: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      }> | null;
      socialLinks: Array<{
        icon: "facebook" | null;
        label: string | null;
        href: string | null;
      }> | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "flooringService"] | order(order asc){    slug,    name,    shortName,    descriptor,    icon,    plankColor,    homeBlurb,    homeFeatures,    servicesBlurb,    servicesFeatures,    image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},    specs  }
export type SERVICES_QUERY_RESULT = Array<{
  slug: "hybrid" | "laminate" | "timber" | null;
  name: string | null;
  shortName: string | null;
  descriptor: string | null;
  icon:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users"
    | null;
  plankColor: string | null;
  homeBlurb: string | null;
  homeFeatures: Array<string> | null;
  servicesBlurb: string | null;
  servicesFeatures: Array<string> | null;
  image: {
    alt: string | null;
    decorative: boolean | null;
    hotspot: {
      x: number | null;
      y: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  specs: {
    coreMaterial?: string;
    jankaRating?: string;
    thickness?: string;
    installation?: string;
    waterproof?: string;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROCESS_STEPS_QUERY
// Query: *[_type == "processStep"] | order(order asc){ number, title, description }
export type PROCESS_STEPS_QUERY_RESULT = Array<{
  number: string | null;
  title: string | null;
  description: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: HOME_FAQS_QUERY
// Query: *[_type == "faq" && showOnHome == true] | order(order asc){ question, answer }
export type HOME_FAQS_QUERY_RESULT = Array<{
  question: string | null;
  answer: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FAQ_GROUPS_QUERY
// Query: *[_type == "faqGroup"] | order(order asc){    title,    icon,    "items": *[_type == "faq" && group._ref == ^._id] | order(order asc){ question, answer }  }
export type FAQ_GROUPS_QUERY_RESULT = Array<{
  title: string | null;
  icon:
    | "badge-check"
    | "cleaning"
    | "collections"
    | "construction"
    | "contact"
    | "droplets"
    | "gallery"
    | "gem"
    | "history"
    | "home"
    | "layers"
    | "leaf"
    | "map-pin"
    | "quote"
    | "ruler"
    | "search"
    | "tree-pine"
    | "users"
    | null;
  items: Array<{
    question: string | null;
    answer: string | null;
  }>;
}>;

// Source: src/sanity/queries.ts
// Variable: ALL_FAQS_QUERY
// Query: *[_type == "faq" && defined(group)] | order(order asc){ question, answer }
export type ALL_FAQS_QUERY_RESULT = Array<{
  question: string | null;
  answer: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: GALLERY_PROJECTS_QUERY
// Query: *[_type == "galleryProject"] | order(order asc){    "slug": slug.current,    title,    subtitle,    "category": category->slug,    sector,    aspect,    image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},    "caseStudy": caseStudy->slug.current  }
export type GALLERY_PROJECTS_QUERY_RESULT = Array<{
  slug: string | null;
  title: string | null;
  subtitle: string | null;
  category: "hybrid" | "laminate" | "timber" | null;
  sector: "Commercial" | "Residential" | null;
  aspect:
    | "aspect-[3/2]"
    | "aspect-[3/4]"
    | "aspect-[4/3]"
    | "aspect-[4/5]"
    | "aspect-square"
    | null;
  image: {
    alt: string | null;
    decorative: boolean | null;
    hotspot: {
      x: number | null;
      y: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  caseStudy: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current }
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    "slug": slug.current,    "category": category->slug,    eyebrow,    title,    shortTitle,    summary,    order,    hero {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},    meta[]{ label, value },    challenge{ heading, body, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }} },    solution{ heading, body, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}, stats[]{ value, label } },    features{ heading, description, items[] { icon, title, description } },    specs{ heading, description, rows[]{ attribute, value } },    details{ heading, rows[]{ label, value } },    roadmap{ heading, description, steps[] { icon, title, description } },    gallery{ heading, images[] {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }} },    testimonial{ quote, name, role, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }} },    cta{ heading, description, primary { label, href }, secondary { label, href } },    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type CASE_STUDY_QUERY_RESULT = {
  slug: string | null;
  category: "hybrid" | "laminate" | "timber" | null;
  eyebrow: string | null;
  title: string | null;
  shortTitle: string | null;
  summary: string | null;
  order: number | null;
  hero: {
    alt: string | null;
    decorative: boolean | null;
    hotspot: {
      x: number | null;
      y: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  meta: Array<{
    label: string | null;
    value: string | null;
  }> | null;
  challenge: {
    heading: string | null;
    body: string | null;
    image: {
      alt: string | null;
      decorative: boolean | null;
      hotspot: {
        x: number | null;
        y: number | null;
      } | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  solution: {
    heading: string | null;
    body: string | null;
    image: {
      alt: string | null;
      decorative: boolean | null;
      hotspot: {
        x: number | null;
        y: number | null;
      } | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    stats: Array<{
      value: string | null;
      label: string | null;
    }> | null;
  } | null;
  features: {
    heading: string | null;
    description: string | null;
    items: Array<{
      icon:
        | "badge-check"
        | "cleaning"
        | "collections"
        | "construction"
        | "contact"
        | "droplets"
        | "gallery"
        | "gem"
        | "history"
        | "home"
        | "layers"
        | "leaf"
        | "map-pin"
        | "quote"
        | "ruler"
        | "search"
        | "tree-pine"
        | "users"
        | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  specs: {
    heading: string | null;
    description: string | null;
    rows: Array<{
      attribute: string | null;
      value: string | null;
    }> | null;
  } | null;
  details: {
    heading: string | null;
    rows: Array<{
      label: string | null;
      value: string | null;
    }> | null;
  } | null;
  roadmap: {
    heading: string | null;
    description: string | null;
    steps: Array<{
      icon:
        | "badge-check"
        | "cleaning"
        | "collections"
        | "construction"
        | "contact"
        | "droplets"
        | "gallery"
        | "gem"
        | "history"
        | "home"
        | "layers"
        | "leaf"
        | "map-pin"
        | "quote"
        | "ruler"
        | "search"
        | "tree-pine"
        | "users"
        | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  gallery: {
    heading: string | null;
    images: Array<{
      alt: string | null;
      decorative: boolean | null;
      hotspot: {
        x: number | null;
        y: number | null;
      } | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    }> | null;
  } | null;
  testimonial: {
    quote: string | null;
    name: string | null;
    role: string | null;
    image: {
      alt: string | null;
      decorative: boolean | null;
      hotspot: {
        x: number | null;
        y: number | null;
      } | null;
      crop: {
        top: number | null;
        bottom: number | null;
        left: number | null;
        right: number | null;
      } | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  cta: {
    heading: string | null;
    description: string | null;
    primary: {
      label: string | null;
      href: string | null;
    } | null;
    secondary: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogEyebrow: string | null;
    ogDescription: string | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: NEXT_CASE_STUDY_QUERY
// Query: coalesce(    *[_type == "caseStudy" && order > $order] | order(order asc)[0],    *[_type == "caseStudy"] | order(order asc)[0]  ){    "slug": slug.current,    shortTitle,    eyebrow,    hero {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}  }
export type NEXT_CASE_STUDY_QUERY_RESULT = {
  slug: string | null;
  shortTitle: string | null;
  eyebrow: string | null;
  hero: {
    alt: string | null;
    decorative: boolean | null;
    hotspot: {
      x: number | null;
      y: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: CASE_STUDY_OG_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{ title, eyebrow, summary }
export type CASE_STUDY_OG_QUERY_RESULT = {
  title: string | null;
  eyebrow: string | null;
  summary: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }},    servicesHeading { eyebrow, title, description },    qualityBand{      title,      description,      image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},      statLabel,      points[] { icon, title, description }    },    galleryHeading{ eyebrow, title, link { label, href } },    bentoTiles[]{      span,      "project": project->{        title,        subtitle,        "slug": slug.current,        "category": category->slug,        "caseStudy": caseStudy->slug.current,        image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}      }    },    faqSection{ heading { eyebrow, title, description }, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}, link { label, href } },    contactSection{      formTitle,      formDescription,      title,      description,      channelLabels,      mapImage {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}    },    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      servicesHeading: null;
      qualityBand: null;
      galleryHeading: null;
      bentoTiles: null;
      faqSection: null;
      contactSection: null;
      seo: null;
    }
  | {
      hero: null;
      servicesHeading: null;
      qualityBand: null;
      galleryHeading: null;
      bentoTiles: null;
      faqSection: null;
      contactSection: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      servicesHeading: null;
      qualityBand: null;
      galleryHeading: null;
      bentoTiles: null;
      faqSection: null;
      contactSection: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      servicesHeading: null;
      qualityBand: null;
      galleryHeading: null;
      bentoTiles: null;
      faqSection: null;
      contactSection: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      servicesHeading: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      qualityBand: {
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        statLabel: string | null;
        points: Array<{
          icon:
            | "badge-check"
            | "cleaning"
            | "collections"
            | "construction"
            | "contact"
            | "droplets"
            | "gallery"
            | "gem"
            | "history"
            | "home"
            | "layers"
            | "leaf"
            | "map-pin"
            | "quote"
            | "ruler"
            | "search"
            | "tree-pine"
            | "users"
            | null;
          title: string | null;
          description: string | null;
        }> | null;
      } | null;
      galleryHeading: {
        eyebrow: string | null;
        title: string | null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      bentoTiles: Array<{
        span: "" | "md:col-span-2 md:row-span-2" | "md:col-span-2" | null;
        project: {
          title: string | null;
          subtitle: string | null;
          slug: string | null;
          category: "hybrid" | "laminate" | "timber" | null;
          caseStudy: string | null;
          image: {
            alt: string | null;
            decorative: boolean | null;
            hotspot: {
              x: number | null;
              y: number | null;
            } | null;
            crop: {
              top: number | null;
              bottom: number | null;
              left: number | null;
              right: number | null;
            } | null;
            asset: {
              _id: string;
              url: string | null;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }> | null;
      faqSection: {
        heading: {
          eyebrow: string | null;
          title: string | null;
          description: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      contactSection: {
        formTitle: string | null;
        formDescription: string | null;
        title: string | null;
        description: string | null;
        channelLabels: {
          phone?: string;
          email?: string;
          address?: string;
        } | null;
        mapImage: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_id == "servicesPage"][0]{    hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }},    comparisonHeading { eyebrow, title, description },    processHeading { eyebrow, title, description },    processFootnote,    cta {  title,  description,  primary { label, href },  secondary { label, href },  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}},    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type SERVICES_PAGE_QUERY_RESULT =
  | {
      hero: null;
      comparisonHeading: null;
      processHeading: null;
      processFootnote: null;
      cta: null;
      seo: null;
    }
  | {
      hero: null;
      comparisonHeading: null;
      processHeading: null;
      processFootnote: null;
      cta: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      comparisonHeading: null;
      processHeading: null;
      processFootnote: null;
      cta: {
        title: null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      comparisonHeading: null;
      processHeading: null;
      processFootnote: null;
      cta: {
        title: string | null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      comparisonHeading: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      processHeading: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      processFootnote: string | null;
      cta: {
        title: string | null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: GALLERY_PAGE_QUERY
// Query: *[_id == "galleryPage"][0]{ hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }}, cta {  title,  description,  primary { label, href },  secondary { label, href },  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}}, seo { metaTitle, metaDescription, ogEyebrow, ogDescription } }
export type GALLERY_PAGE_QUERY_RESULT =
  | {
      hero: null;
      cta: null;
      seo: null;
    }
  | {
      hero: null;
      cta: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      cta: {
        title: null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      cta: {
        title: string | null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: NOT_FOUND_PAGE_QUERY
// Query: *[_id == "notFoundPage"][0]{    image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},    icon,    heading,    description,    actions[] { icon, label, href },    helpPanel{ title, links[] { label, href } },    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type NOT_FOUND_PAGE_QUERY_RESULT =
  | {
      image: null;
      icon: null;
      heading: null;
      description: null;
      actions: null;
      helpPanel: null;
      seo: null;
    }
  | {
      image: null;
      icon: null;
      heading: null;
      description: null;
      actions: null;
      helpPanel: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      image: {
        alt: string | null;
        decorative: boolean | null;
        hotspot: {
          x: number | null;
          y: number | null;
        } | null;
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      icon: null;
      heading: null;
      description: null;
      actions: null;
      helpPanel: null;
      seo: null;
    }
  | {
      image: null;
      icon:
        | "badge-check"
        | "cleaning"
        | "collections"
        | "construction"
        | "contact"
        | "droplets"
        | "gallery"
        | "gem"
        | "history"
        | "home"
        | "layers"
        | "leaf"
        | "map-pin"
        | "quote"
        | "ruler"
        | "search"
        | "tree-pine"
        | "users"
        | null;
      heading: null;
      description: null;
      actions: null;
      helpPanel: null;
      seo: null;
    }
  | {
      image: {
        alt: string | null;
        decorative: boolean | null;
        hotspot: {
          x: number | null;
          y: number | null;
        } | null;
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      icon:
        | "badge-check"
        | "cleaning"
        | "collections"
        | "construction"
        | "contact"
        | "droplets"
        | "gallery"
        | "gem"
        | "history"
        | "home"
        | "layers"
        | "leaf"
        | "map-pin"
        | "quote"
        | "ruler"
        | "search"
        | "tree-pine"
        | "users"
        | null;
      heading: null;
      description: null;
      actions: null;
      helpPanel: null;
      seo: null;
    }
  | {
      image: null;
      icon: null;
      heading: null;
      description: string | null;
      actions: null;
      helpPanel: null;
      seo: null;
    }
  | {
      image: {
        alt: string | null;
        decorative: boolean | null;
        hotspot: {
          x: number | null;
          y: number | null;
        } | null;
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      icon:
        | "badge-check"
        | "cleaning"
        | "collections"
        | "construction"
        | "contact"
        | "droplets"
        | "gallery"
        | "gem"
        | "history"
        | "home"
        | "layers"
        | "leaf"
        | "map-pin"
        | "quote"
        | "ruler"
        | "search"
        | "tree-pine"
        | "users"
        | null;
      heading: string | null;
      description: string | null;
      actions: Array<{
        icon:
          | "badge-check"
          | "cleaning"
          | "collections"
          | "construction"
          | "contact"
          | "droplets"
          | "gallery"
          | "gem"
          | "history"
          | "home"
          | "layers"
          | "leaf"
          | "map-pin"
          | "quote"
          | "ruler"
          | "search"
          | "tree-pine"
          | "users"
          | null;
        label: string | null;
        href: string | null;
      }> | null;
      helpPanel: {
        title: string | null;
        links: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }},    stats[]{ icon, title, description, inverted },    missionStory{ eyebrow, title, body, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}, action { label, href } },    craftCards[]{ title, description, image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }} },    specTable{ heading, description, rows[]{ type, durability, idealFor, warranty } },    cta {  title,  description,  primary { label, href },  secondary { label, href },  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }}},    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      hero: null;
      stats: null;
      missionStory: null;
      craftCards: null;
      specTable: null;
      cta: null;
      seo: null;
    }
  | {
      hero: null;
      stats: null;
      missionStory: null;
      craftCards: null;
      specTable: null;
      cta: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      stats: null;
      missionStory: null;
      craftCards: null;
      specTable: null;
      cta: {
        title: null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      stats: null;
      missionStory: null;
      craftCards: null;
      specTable: null;
      cta: {
        title: string | null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      stats: Array<{
        icon: string | null;
        title: string | null;
        description: string | null;
        inverted: boolean | null;
      }> | null;
      missionStory: {
        eyebrow: string | null;
        title: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        action: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      craftCards: Array<{
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      }> | null;
      specTable: {
        heading: string | null;
        description: string | null;
        rows: Array<{
          type: string | null;
          durability: string | null;
          idealFor: string | null;
          warranty: string | null;
        }> | null;
      } | null;
      cta: {
        title: string | null;
        description: string | null;
        primary: {
          label: string | null;
          href: string | null;
        } | null;
        secondary: {
          label: string | null;
          href: string | null;
        } | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: FAQ_PAGE_QUERY
// Query: *[_id == "faqPage"][0]{    hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }},    searchPlaceholder,    supportCard{ title, description, emailLabel },    closingBand { title, description, actions[] { label, href } },    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type FAQ_PAGE_QUERY_RESULT =
  | {
      hero: null;
      searchPlaceholder: null;
      supportCard: null;
      closingBand: null;
      seo: null;
    }
  | {
      hero: null;
      searchPlaceholder: null;
      supportCard: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      searchPlaceholder: null;
      supportCard: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      searchPlaceholder: null;
      supportCard: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      searchPlaceholder: null;
      supportCard: null;
      closingBand: {
        title: string | null;
        description: string | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      searchPlaceholder: string | null;
      supportCard: {
        title: string | null;
        description: string | null;
        emailLabel: string | null;
      } | null;
      closingBand: {
        title: string | null;
        description: string | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    hero {  eyebrow,  title,  description,  image {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},  actions[] { label, href }},    avatars[] {  alt,  decorative,  hotspot { x, y },  crop { top, bottom, left, right },  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  }},    socialProof{ prefix, highlightSuffix, suffix },    closingBand { title, description, actions[] { label, href } },    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      hero: null;
      avatars: null;
      socialProof: null;
      closingBand: null;
      seo: null;
    }
  | {
      hero: null;
      avatars: null;
      socialProof: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: null;
        description: null;
        image: null;
        actions: null;
      } | null;
      avatars: null;
      socialProof: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      avatars: null;
      socialProof: null;
      closingBand: null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      avatars: null;
      socialProof: null;
      closingBand: {
        title: string | null;
        description: string | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          alt: string | null;
          decorative: boolean | null;
          hotspot: {
            x: number | null;
            y: number | null;
          } | null;
          crop: {
            top: number | null;
            bottom: number | null;
            left: number | null;
            right: number | null;
          } | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
        } | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      avatars: Array<{
        alt: string | null;
        decorative: boolean | null;
        hotspot: {
          x: number | null;
          y: number | null;
        } | null;
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      }> | null;
      socialProof: {
        prefix: string | null;
        highlightSuffix: string | null;
        suffix: string | null;
      } | null;
      closingBand: {
        title: string | null;
        description: string | null;
        actions: Array<{
          label: string | null;
          href: string | null;
        }> | null;
      } | null;
      seo: {
        metaTitle: string | null;
        metaDescription: string | null;
        ogEyebrow: string | null;
        ogDescription: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: {    "caseStudies": *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current },    "navItems": *[_id == "siteSettings"][0].navItems[]{ href }  }
export type SITEMAP_QUERY_RESULT = {
  caseStudies: Array<{
    slug: string | null;
  }>;
  navItems: Array<{
    href: string | null;
  }> | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    name,\n    legalName,\n    tagline,\n    description,\n    blurb,\n    keywords,\n    stats{ yearsExperience, familiesServed },\n    contact,\n    hours[]{ days, short, time, closed },\n    hoursSummary,\n    openingHoursSpec,\n    serviceAreas,\n    navItems[]{ label, href },\n    footerColumns[]{ title, links[]{ label, href } },\n    socialLinks[]{ icon, label, href }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "flooringService"] | order(order asc){\n    slug,\n    name,\n    shortName,\n    descriptor,\n    icon,\n    plankColor,\n    homeBlurb,\n    homeFeatures,\n    servicesBlurb,\n    servicesFeatures,\n    image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n    specs\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "processStep"] | order(order asc){ number, title, description }\n': PROCESS_STEPS_QUERY_RESULT;
    '\n  *[_type == "faq" && showOnHome == true] | order(order asc){ question, answer }\n': HOME_FAQS_QUERY_RESULT;
    '\n  *[_type == "faqGroup"] | order(order asc){\n    title,\n    icon,\n    "items": *[_type == "faq" && group._ref == ^._id] | order(order asc){ question, answer }\n  }\n': FAQ_GROUPS_QUERY_RESULT;
    '\n  *[_type == "faq" && defined(group)] | order(order asc){ question, answer }\n': ALL_FAQS_QUERY_RESULT;
    '\n  *[_type == "galleryProject"] | order(order asc){\n    "slug": slug.current,\n    title,\n    subtitle,\n    "category": category->slug,\n    sector,\n    aspect,\n    image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n    "caseStudy": caseStudy->slug.current\n  }\n': GALLERY_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current }\n': CASE_STUDY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && slug.current == $slug][0]{\n    "slug": slug.current,\n    "category": category->slug,\n    eyebrow,\n    title,\n    shortTitle,\n    summary,\n    order,\n    hero {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n    meta[]{ label, value },\n    challenge{ heading, body, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n} },\n    solution{ heading, body, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}, stats[]{ value, label } },\n    features{ heading, description, items[] { icon, title, description } },\n    specs{ heading, description, rows[]{ attribute, value } },\n    details{ heading, rows[]{ label, value } },\n    roadmap{ heading, description, steps[] { icon, title, description } },\n    gallery{ heading, images[] {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n} },\n    testimonial{ quote, name, role, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n} },\n    cta{ heading, description, primary { label, href }, secondary { label, href } },\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': CASE_STUDY_QUERY_RESULT;
    '\n  coalesce(\n    *[_type == "caseStudy" && order > $order] | order(order asc)[0],\n    *[_type == "caseStudy"] | order(order asc)[0]\n  ){\n    "slug": slug.current,\n    shortTitle,\n    eyebrow,\n    hero {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n  }\n': NEXT_CASE_STUDY_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && slug.current == $slug][0]{ title, eyebrow, summary }\n': CASE_STUDY_OG_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n},\n    servicesHeading { eyebrow, title, description },\n    qualityBand{\n      title,\n      description,\n      image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n      statLabel,\n      points[] { icon, title, description }\n    },\n    galleryHeading{ eyebrow, title, link { label, href } },\n    bentoTiles[]{\n      span,\n      "project": project->{\n        title,\n        subtitle,\n        "slug": slug.current,\n        "category": category->slug,\n        "caseStudy": caseStudy->slug.current,\n        image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n      }\n    },\n    faqSection{ heading { eyebrow, title, description }, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}, link { label, href } },\n    contactSection{\n      formTitle,\n      formDescription,\n      title,\n      description,\n      channelLabels,\n      mapImage {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n    },\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "servicesPage"][0]{\n    hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n},\n    comparisonHeading { eyebrow, title, description },\n    processHeading { eyebrow, title, description },\n    processFootnote,\n    cta {\n  title,\n  description,\n  primary { label, href },\n  secondary { label, href },\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n},\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': SERVICES_PAGE_QUERY_RESULT;
    '\n  *[_id == "galleryPage"][0]{ hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n}, cta {\n  title,\n  description,\n  primary { label, href },\n  secondary { label, href },\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n}, seo { metaTitle, metaDescription, ogEyebrow, ogDescription } }\n': GALLERY_PAGE_QUERY_RESULT;
    '\n  *[_id == "notFoundPage"][0]{\n    image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n    icon,\n    heading,\n    description,\n    actions[] { icon, label, href },\n    helpPanel{ title, links[] { label, href } },\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': NOT_FOUND_PAGE_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0]{\n    hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n},\n    stats[]{ icon, title, description, inverted },\n    missionStory{ eyebrow, title, body, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}, action { label, href } },\n    craftCards[]{ title, description, image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n} },\n    specTable{ heading, description, rows[]{ type, durability, idealFor, warranty } },\n    cta {\n  title,\n  description,\n  primary { label, href },\n  secondary { label, href },\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n}\n},\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "faqPage"][0]{\n    hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n},\n    searchPlaceholder,\n    supportCard{ title, description, emailLabel },\n    closingBand { title, description, actions[] { label, href } },\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': FAQ_PAGE_QUERY_RESULT;
    '\n  *[_id == "contactPage"][0]{\n    hero {\n  eyebrow,\n  title,\n  description,\n  image {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n  actions[] { label, href }\n},\n    avatars[] {\n  alt,\n  decorative,\n  hotspot { x, y },\n  crop { top, bottom, left, right },\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  }\n},\n    socialProof{ prefix, highlightSuffix, suffix },\n    closingBand { title, description, actions[] { label, href } },\n    seo { metaTitle, metaDescription, ogEyebrow, ogDescription }\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  {\n    "caseStudies": *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current },\n    "navItems": *[_id == "siteSettings"][0].navItems[]{ href }\n  }\n': SITEMAP_QUERY_RESULT;
  }
}
